### ISSUE TITLE
Should From<String> convert to inline if possible?

### ISSUE THREAD

**Issue by arthurprs** [ParkMyCar/compact_str#227]
I was profiling something and noticed that `CompactString::clone` was hitting the allocator consistently even though the strings were small. Turns out that if you convert a String into CompactString using the From/Into trait it'll do so by taking ownership of the backing allocation as expected. But as a side-effect further clones will behave like String::clone _even_ if the strings would fit inline.

If you are using CompactString chances are you expect it to be inlineable most of the time so this comes as a performance pitfall depending on how the CompactString was created.

I suggest changing `From<String>` to convert to inline if possible to avoid this scenario. Doing so may make `From<CompactString> for String` slower but I'll argue that an allocation is expected in this case and any re-use is a bonus. Alternatively the Clone implementation can check if the clone should be inline even if the source is boxed.

One could also argue for full flexibility and that the behavior should be kept and a new function added `CompacString::compact`, but it's both cumbersome to use and most people will never realize it's thing. If such hyperspecific apis are desirable I suggest  a different constructor that keeps the exiting behavior `CompactString::from_string_buffer`.

**Comment by ParkMyCar** [comment]
Hey @arthurprs, thanks for filling this issue!

Inlining small strings during `From<String>` is something I've gone back and forth on. Originally I opted not to because it would then require us to de-allocate the `String` which would be relatively slow, but your use case of then `Clone`-ing the `CompactString` and frequently hitting the allocator is definitely bad.

I kind of like the approach that on `Clone` if the `CompactString` is small enough, inline it then? That would then result in this behavior:

```
fn main() {
  let x = "hello world".to_string();

  let a = CompactString::from(x);
  let b = a.clone();

  assert_ne!(a.is_heap_allocated(), b.is_heap_allocated());
}
```

Which I think is okay? Whether or not a `CompactString` is inlined or not to me seems sort of like an implementation detail. Only inlining on `Clone` instead of on `From<String>` would make sure we reduce trips to the allocator as much as possible.

Note: Currently when modifying a heap allocated short `CompactString` we'll inline then, e.g. the following test passes:
```
#[test]
fn test_from_string_inlines_on_push() {
    let mut compact = CompactString::from("hello".to_string());
    assert!(compact.is_heap_allocated());

    compact.push_str(" world");
    // when growing the CompactString we should inline it
    assert!(!compact.is_heap_allocated());
}
```

Note2: @krallin do you have any thoughts on this? I see when you started using `compact_str` in https://github.com/facebookincubator/buck2/commit/2754a60407767ebe3438932609dc40b3a9f1da48 you also mentioned not inlining on `From<String>` as a negative

**Comment by NobodyXu** [comment]
> Only inlining on Clone instead of on From<String> would make sure we reduce trips to the allocator as much as possible.

I would definitely want `<CompactString as Clone>::clone` to inline the string if possible!

Also, I think you could also manually implement `<CompactString as Clone>::clone_from` to avoid heap allocation if the destination already has a large enough buffer allocated on heap.

**Comment by krallin** [comment]
> Note2: @krallin <https://github.com/krallin> do you have any thoughts on
this? I see when you started using compact_str in facebookincubator/buck2@
2754a60
<https://github.com/facebookincubator/buck2/commit/2754a60407767ebe3438932609dc40b3a9f1da48>
you
also mentioned not inlining on From<String> as a negative

The intention for us using small strings is to reduce memory size, so
that’s indeed a negative as it makes it harder to understand how exactly a
given small string is represented based only on the types (you need to know
its provenance too).

It’s not something we can’t work around, but it seemed like a footgun that
only precise profiling would let you spot

**Comment by ParkMyCar** [comment]
> I would definitely want <CompactString as Clone>::clone to inline the string if possible!

Sweet! I just put up #254 which implements this

> The intention for us using small strings is to reduce memory size, so that’s indeed a negative as it makes it harder to understand how exactly a given small string is represented based only on the types (you need to know its provenance too). It’s not something we can’t work around, but it seemed like a footgun that only precise profiling would let you spot

That makes sense, thanks for the input!

It seems like inlining strings when possible (even if it results in a de-allocation) is the expected behavior, because of this I propose the following changes:
1. `From<String>` and `From<Box<str>>` will inline strings whose _length_ is <= 24 bytes
    - today these strings will remain heap allocated
2. Add a new API `CompactString::from_string_buffer` that does not inline strings whose length is <= 24 bytes, with a doc comment explaining why this API exists
3. Update the `Clone` impl to inline strings when a `CompactString` has a _capacity_ <= 24 bytes
    - inlining based on capacity seems like the most "correct" thing to do here, but I could be convinced to inline based on length instead

Note: we could add an additional API, something like `CompactString::from_owned_box_str` that preserves the existing behavior of `From<Box<str>>`, but IMO that wouldn't be frequently used and would further complicate the API of `CompactString`, so to me leaving it out seems reasonable.

Thoughts?

**Comment by NobodyXu** [comment]
This sounds good to me!

**Comment by ParkMyCar** [comment]
Opened #254 and #256 which implements the above changes
