### ISSUE TITLE
[RUSTSEC-2024-0363] Support sqlx 0.8

### ISSUE THREAD

**Issue by rshigapov-bhft** [ParkMyCar/compact_str#407]
sqlx 0.8 has fixed [RUSTSEC-2024-0363.](https://rustsec.org/advisories/RUSTSEC-2024-0363.html)

I see two ways to support it:

* drop sqlx 0.7 support and implement support for sqlx 0.8
* add an extra feature like "sqlx-07" that allows users to keep working with sqlx 0.7 until they migrate to sqlx 0.8

**Comment by ParkMyCar** [comment]
Thanks for the heads up! I'll publish a `v0.8.1` and `v0.7.2` that has a `sqlx_08` feature, which should be semver compatible and allow folks to opt into sqlx 0.8 if need be

**Comment by ParkMyCar** [comment]
Darn, the above approach doesn't work because of https://github.com/rust-lang/cargo/issues/10801. We can't have sqlx 0.7 and 0.8 even if both are optional dependencies because Cargo tries to include both in the lockfile and bails because both link `sqlite3` but at different versions.

I'll make this change on `main` and push a `0.9.0-beta.1`
